### ISSUE TITLE
IsNewDeposit iterates incorrectly

### ISSUE THREAD

**Issue by oblotzky** [athielking/Addon#27]
Lines 389 and 390 in main.lua

`    for j=1, # historyDeposits do`
`        local historyDeposit = historyDeposits[i]`

the index used in the brackets of the second line should be j not i as i is used to iterate one level above

while at it, maybe remove the space after # in the first line, just nitpicking, seems LUA doesn't care, just I don't see it anywhere else like this in the code.

**Comment by ClassicGuildBank** [comment]
fixed in PR #28
