### ISSUE TITLE
No area to change user account password

### ISSUE THREAD

**Issue by collinjdoyle** [athielking/Addon#6]
Currently no way to change user passwords.

Otherwise, great site and addon. Keep up the good work. I will be donating soon.

**Comment by athielking** [comment]
The forgot password link has been updated.  It 'worked' before but there was no error handling so there was no notification of if the link was sent or if there was an error.   You should be able to update your password using this now.

![image](https://user-images.githubusercontent.com/18670550/64906744-18ce2380-d6b8-11e9-8650-12fd620b2c6e.png)
